// "What would my street look like in a storm?" — these replace the forecast
// with a named condition. Everything downstream treats them exactly like a
// real reading, so an override is a full simulation, not a filter.

export const OVERRIDES = {
  clear: {
    weatherCode: 0,
    cloudCover: 3,
    precipitation: 0,
    rain: 0,
    snowfall: 0,
    visibility: 24000,
    humidity: 42,
  },
  partly: {
    weatherCode: 2,
    cloudCover: 45,
    precipitation: 0,
    rain: 0,
    snowfall: 0,
    visibility: 18000,
    humidity: 55,
  },
  overcast: {
    weatherCode: 3,
    cloudCover: 98,
    precipitation: 0,
    rain: 0,
    snowfall: 0,
    visibility: 12000,
    humidity: 72,
  },
  fog: {
    weatherCode: 45,
    cloudCover: 90,
    precipitation: 0,
    rain: 0,
    snowfall: 0,
    visibility: 220,
    humidity: 97,
    windSpeed: 1,
  },
  drizzle: {
    weatherCode: 53,
    cloudCover: 92,
    precipitation: 0.4,
    rain: 0.4,
    snowfall: 0,
    visibility: 7000,
    humidity: 89,
  },
  rain: {
    weatherCode: 63,
    cloudCover: 100,
    precipitation: 4.5,
    rain: 4.5,
    snowfall: 0,
    visibility: 4200,
    humidity: 93,
    windSpeed: 7,
  },
  storm: {
    weatherCode: 95,
    cloudCover: 100,
    precipitation: 11,
    rain: 11,
    snowfall: 0,
    visibility: 2600,
    humidity: 95,
    windSpeed: 13,
    windGust: 22,
  },
  snow: {
    weatherCode: 73,
    cloudCover: 97,
    precipitation: 1.6,
    rain: 0,
    snowfall: 1.6,
    snowDepth: 0.06,
    visibility: 1800,
    humidity: 88,
    temperature: -2,
    windSpeed: 5,
  },
};
